name = "iceberg"
main = "build/index.js"
compatibility_date = "2024-04-05"

vars = { WHITELIST = "penqguin" }

[env.production]
# Add production-specific settings here (route, zone_id, etc.)
# Example: route = "example.com/*"
